"""Deterministic Python generation from Candid service specifications."""

import hashlib

GENERATOR_VERSION = "1"


def _type(spec):
    if spec.kind in ("opt", "vec"):
        return "TypeSpec.%s(%s)" % (spec.kind, _type(spec.inner))
    if spec.kind in ("record", "variant"):
        fields = ", ".join("%r: %s" % (name, _type(value)) for name, value in spec.fields)
        return "TypeSpec.%s({%s})" % (spec.kind, fields)
    return "TypeSpec(%r)" % spec.kind


def generate(source, class_name, parser=None):
    if not class_name.isidentifier(): raise ValueError("generated service name must be a Python identifier")
    if parser is None:
        from pyre._candid_parser import parse
        parser = parse
    service = parser(source)
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    lines = [
        '"""Generated by PYRE Candid generator %s; source sha256: %s."""' % (GENERATOR_VERSION, digest),
        "from pyre.candid import MethodSpec, ServiceSpec, TypeSpec", "",
        "%s = ServiceSpec([" % class_name,
    ]
    for _name, method in service.methods:
        args = ", ".join(_type(item) for item in method.args)
        returns = ", ".join(_type(item) for item in method.returns)
        if len(method.args) == 1: args += ","
        if len(method.returns) == 1: returns += ","
        lines.append("    MethodSpec(%r, (%s), (%s), mode=%r)," % (method.name, args, returns, method.mode))
    lines.extend(["], name=%r)" % class_name, ""])
    return "\n".join(lines)
