"""PYRE canister entrypoint — Kybra glue.

This file is the only place the CDK (Kybra) meets your code. It declares
the ICP HTTP-gateway Candid interface and delegates every request to the
`app` object defined in app.py. Generated by `pyre new`; you normally
never edit it.
"""

from kybra import (
    Alias,
    Async,
    Func,
    Opt,
    Query,
    Record,
    StableBTreeMap,
    Tuple,
    Variant,
    Vec,
    blob,
    ic,
    init,
    nat16,
    nat64,
    post_upgrade,
    query,
    update,
    void,
)
from kybra.canisters.management import HttpResponse, HttpTransformArgs

import pyre.kv
from pyre._lifecycle import run_init, run_post_upgrade
from pyre.gateway import dispatch_query, dispatch_update
from pyre.transform import transform_management_response

from app import app

# pyre.kv's stable-memory backing. Declared here (not inside pyre) because
# Kybra registers StableBTreeMaps by static analysis of the canister source.
pyre_kv_store = StableBTreeMap[str, str](
    memory_id=250, max_key_size=1_024, max_value_size=64_000
)
pyre.kv.bind_backend(pyre_kv_store)


# --- ICP HTTP gateway Candid interface ------------------------------------
# (http-gateway-protocol records; streaming is declared but unused by PYRE)


class Token(Record):
    arbitrary_data: str


class StreamingCallbackHttpResponse(Record):
    body: blob
    token: Opt[Token]


Callback = Func(Query[[Token], StreamingCallbackHttpResponse])


class CallbackStrategy(Record):
    callback: Callback
    token: Token


class StreamingStrategy(Variant, total=False):
    Callback: CallbackStrategy


HeaderField = Alias[Tuple[str, str]]


# Candid matches records structurally, so these names are PYRE-local; they
# avoid colliding with the management canister's HttpResponse.
class HttpGatewayRequest(Record):
    method: str
    url: str
    headers: Vec[HeaderField]
    body: blob


class HttpGatewayResponse(Record):
    status_code: nat16
    headers: Vec[HeaderField]
    body: blob
    streaming_strategy: Opt[StreamingStrategy]
    upgrade: Opt[bool]


# --- canister methods -------------------------------------------------------


@init
def pyre_init() -> void:
    run_init(app)


@post_upgrade
def pyre_post_upgrade() -> void:
    run_post_upgrade(app)


@query
def http_request(req: HttpGatewayRequest) -> HttpGatewayResponse:
    response = dispatch_query(app, req)
    strategy = response.get("streaming_strategy")
    if strategy is not None:
        strategy["Callback"]["callback"] = (ic.id(), "pyre_http_streaming_callback")
    return response


@query
def pyre_http_streaming_callback(token: Token) -> StreamingCallbackHttpResponse:
    from pyre.assets import streaming_callback

    return streaming_callback(token["arbitrary_data"])


@update
def http_request_update(req: HttpGatewayRequest) -> Async[HttpGatewayResponse]:
    return (yield from dispatch_update(app, req))


@query
def pyre_default_transform(args: HttpTransformArgs) -> HttpResponse:
    """Determinism transform applied to every outcall response (§5.1)."""
    return transform_management_response(args["response"])


@query
def pyre_perf_probe(url: str) -> nat64:
    """Instruction count for one query dispatch — for §5.4 budget records."""
    dispatch_query(app, {"method": "GET", "url": url, "headers": [], "body": b""})
    return ic.performance_counter(0)
