"""PYRE canister entrypoint — Kybra glue.

This file is the only place the CDK (Kybra) meets your code. It declares
the ICP HTTP-gateway Candid interface and delegates every request to the
`app` object defined in app.py. Generated by `pyre new`; you normally
never edit it.
"""

from kybra import (
    Alias,
    Async,
    Func,
    Opt,
    Query,
    Record,
    StableBTreeMap,
    Tuple,
    Variant,
    Vec,
    blob,
    ic,
    init,
    nat16,
    nat64,
    post_upgrade,
    query,
    update,
    void,
)
from kybra.canisters.management import HttpResponse, HttpTransformArgs

import pyre.kv
from pyre import oidc
from pyre.gateway import dispatch_query, dispatch_update
from pyre.transform import transform_management_response

from app import app, sync_certified_routes

# pyre.kv's stable-memory backing. Declared here (not inside pyre) because
# Kybra registers StableBTreeMaps by static analysis of the canister source.
pyre_kv_store = StableBTreeMap[str, str](
    memory_id=250, max_key_size=1_024, max_value_size=64_000
)
pyre.kv.bind_backend(pyre_kv_store)


# --- ICP HTTP gateway Candid interface ------------------------------------
# (http-gateway-protocol records; streaming is declared but unused by PYRE)


class Token(Record):
    arbitrary_data: str


class StreamingCallbackHttpResponse(Record):
    body: blob
    token: Opt[Token]


Callback = Func(Query[[Token], StreamingCallbackHttpResponse])


class CallbackStrategy(Record):
    callback: Callback
    token: Token


class StreamingStrategy(Variant, total=False):
    Callback: CallbackStrategy


HeaderField = Alias[Tuple[str, str]]


# Candid matches records structurally, so these names are PYRE-local; they
# avoid colliding with the management canister's HttpResponse.
class HttpGatewayRequest(Record):
    method: str
    url: str
    headers: Vec[HeaderField]
    body: blob


class HttpGatewayResponse(Record):
    status_code: nat16
    headers: Vec[HeaderField]
    body: blob
    streaming_strategy: Opt[StreamingStrategy]
    upgrade: Opt[bool]


# --- canister methods -------------------------------------------------------


@init
def pyre_init() -> void:
    # Rebuild per-post certified routes from stored data, then certify route
    # snapshots (and the skip-certification wildcard) so query responses
    # verify against certified data from the first request.
    sync_certified_routes()
    app.recertify()


@post_upgrade
def pyre_post_upgrade() -> void:
    # Dynamic per-post routes live in heap memory, not the code, so they must
    # be rebuilt from the (upgrade-surviving) stable data after every upgrade.
    sync_certified_routes()
    app.recertify()


@query
def http_request(req: HttpGatewayRequest) -> HttpGatewayResponse:
    return dispatch_query(app, req)


@update
def http_request_update(req: HttpGatewayRequest) -> Async[HttpGatewayResponse]:
    return (yield from dispatch_update(app, req))


@query
def pyre_default_transform(args: HttpTransformArgs) -> HttpResponse:
    """Determinism transform applied to every outcall response (§5.1)."""
    return transform_management_response(args["response"])


@query
def pyre_oidc_jwks_transform(args: HttpTransformArgs) -> HttpResponse:
    """Phase C: canonicalize Google's JWKS so all replicas agree byte-for-byte
    (its JSON field ordering is not stable across Google's backends). Required
    by pyre.oidc for the JWKS outcall on a `kid` cache-miss."""
    return oidc.transform_jwks_response(args["response"])


@query
def pyre_perf_probe(url: str) -> nat64:
    """Instruction count for one query dispatch — for §5.4 budget records."""
    dispatch_query(app, {"method": "GET", "url": url, "headers": [], "body": b""})
    return ic.performance_counter(0)
